#!/bin/bash 

minDir="/cygdrive/c/Qt/5.8/mingw53_32/"
secondMinDir="/cygdrive/c/Qt/5.8/mingw53_32/lib/";
libDir="/opt/GitHub/tjlutils"
buildDir="/opt/LibraryBuilds/tjlutils/Debug/debug"
sysDir="/cygdrive/c/Windows/SysWOW64/"
binDir="/cygdrive/c/Users/Public/Public Programs/"

if ! [[ -d "$binDir" ]]; then
    mkdir "$binDir"
fi

rm -f "$minDir/systemcommand.h"
rm -f "$minDir/pythoncrypto.h"
rm -f "$minDir/fileutilities.h"
rm -f "$minDir/mathutilities.h"
rm -f "$minDir/generalutilities.h"
rm -f "$minDir/datetime.h"
rm -f "$minDir/serialport.h"
rm -f "$minDir/eventtimer.h"
rm -f "$minDir/prettyprinter.h"
rm -f "$minDir/udpserver.h"
rm -f "$minDir/udpclient.h"
rm -f "$minDir/udpduplex.h"
rm -f "$minDir/tstream.h"
rm -f "$minDir/tscriptreader.h"
rm -f "$minDir/tscriptexecutor.h"
rm -f "$minDir/stringformat.h"
rm -f "$minDir/bitset.h"

cp "$libDir/systemcommand/systemcommand.h" "$minDir"
cp "$libDir/pythoncrypto/pythoncrypto.h" "$minDir"
cp "$libDir/fileutilities/fileutilities.h" "$minDir"
cp "$libDir/mathutilities/mathutilities.h" "$minDir"
cp "$libDir/generalutilities/generalutilities.h" "$minDir"
cp "$libDir/datetime/datetime.h" "$minDir"
cp "$libDir/templateobjects/templateobjects.h" "$minDir"
cp "$libDir/serialport/serialport.h" "$minDir"
cp "$libDir/prettyprinter/prettyprinter.h" "$minDir"
cp "$libDir/udpserver/udpserver.h" "$minDir"
cp "$libDir/udpclient/udpclient.h" "$minDir"
cp "$libDir/udpduplex/udpduplex.h" "$minDir"
cp "$libDir/tstream/tstream.h" "$minDir"
cp "$libDir/tstream/tscriptreader.h" "$minDir"
cp "$libDir/tstream/tscriptexecutor.h" "$minDir"
cp "$libDir/eventtimer/eventtimer.h" "$minDir"
cp "$libDir/stringformat/stringformat.h" "$minDir"
cp "$libDir/bitset/bitset.h" "$minDir"

cp "$buildDir/tjlutils.dll" "$secondMinDir"
cp "$buildDir/libtjlutils.a" "$secondMinDir"
